import { createContext } from "react";

const userDataContext = createContext({
    userData: [
        {
            key: "1",
            name: "Иванов Петр",
            phoneNumber: "+ 7 (701) 224 35 35",
            need: "Потребность не выбрана",
            date: "21.01.22, 14:02",
            department: "Trade-In / Ross Geller",
            action: "Заявка",
            tags: ["ЮЛ"],
        },
        {
            key: "2",
            name: "+7 (777) 432 11 23",
            need: "Toyota Camry,  Toyota Land Cruiser Prado,  Toyota Corolla",
            date: "21.01.22, 14:02",
            department: "Мой отдел",
            action: "Предпродажа",
            tags: ["ФЛ"],
        },
        {
            key: "3",
            name: "+7 (777) 432 11 23",
            need: "Toyota Camry,  Toyota Land Cruiser Prado,  Toyota Corolla",
            date: "21.01.22, 14:02",
            department: "Мой отдел",
            action: "Предпродажа",
            tags: ["ФЛ"],
        },
        {
            key: "4",
            name: "Саламат",
            need: "Потребность не выбрана",
            date: "21.01.22, 14:02",
            department: "Trade-In / Ross Geller",
            action: "Заявка",
            tags: ["ФЛ"],
        },
        {
            key: "5",
            name: "Азамат",
            need: "Потребность не выбрана",
            date: "21.01.22, 14:02",
            department: "Trade-In / Ross Geller",
            action: "Заявка",
            tags: ["ФЛ"],
        },
        {
            key: "6",
            name: "Алмаз",
            need: "Toyota RAV4",
            date: "21.01.22, 14:02",
            department: "Trade-In / Ross Geller",
            action: "Заявка",
            tags: ["ФЛ"],
        },
        {
            key: "7",
            name: "Наталья",
            need: "Land Cruiser 200",
            date: "21.01.22, 14:02",
            department: "Trade-In / Ross Geller",
            action: "Заявка",
            tags: ["ФЛ"],
        },
        {
            key: "8",
            name: "Дарья",
            need: "Camry 75",
            date: "21.01.22, 14:02",
            department: "Trade-In / Ross Geller",
            action: "Заявка",
            tags: ["ЮЛ"],
        },
        {
            key: "9",
            name: "Фархат",
            need: "Потребность не выбрана",
            date: "21.01.22, 14:02",
            department: "Trade-In / Ross Geller",
            action: "Заявка",
            tags: ["ЮЛ"],
        },
    ],
    setUserData: (data) => {},
});

export default userDataContext;
